import { RolesBuilder } from "nest-access-control";

export const roles: RolesBuilder = new RolesBuilder();

roles
    .grant("USER")
    .readOwn("User")
    .updateOwn("User")

    .grant("STUDENT")
    .extend("USER")
    .readAny("Course")
    .readOwn("Enrollment")
    .createOwn("Enrollment")
    .readOwn("Progress")
    .updateOwn("Progress")

    .grant("TEACHER")
    .extend("USER")
    .readAny("Course")
    .createOwn("Course")
    .updateOwn("Course")
    .deleteOwn("Course")
    .readAny("Student")
    .createAny("Lesson")
    .readAny("Lesson")
    .updateAny("Lesson")
    .deleteAny("Lesson")
    .createAny("Video")
    .readAny("Video")
    .updateAny("Video")
    .deleteAny("Video")
    .createAny("Quiz")
    .readAny("Quiz")
    .updateAny("Quiz")
    .deleteAny("Quiz")
    .createAny("Question")
    .readAny("Question")
    .updateAny("Question")
    .deleteAny("Question")

    .grant("ADMIN")
    .extend("USER")
    .extend("STUDENT")
    .extend("TEACHER")
    .createAny("User")
    .readAny("User")
    .updateAny("User")
    .deleteAny("User")
    .createAny("Course")
    .readAny("Course")
    .updateAny("Course")
    .deleteAny("Course")
    .createAny("Enrollment")
    .readAny("Enrollment")
    .updateAny("Enrollment")
    .deleteAny("Enrollment")
    .createAny("Progress")
    .readAny("Progress")
    .updateAny("Progress")
    .deleteAny("Progress");
